#! /usr/bin/env python

from pet import engine
from pet.sql import DBUpdater

from argparse import ArgumentParser
import sys

parser = ArgumentParser(description='create and update database schema for PET')
parser.add_argument('-c', '--create', action='store_true', default=False)
options = parser.parse_args(sys.argv[1:])

DBUpdater().run(engine=engine(), create_database=options.create)
