#! /usr/bin/env python

from pet.models import *
from pet.classifier import Classifier

session = Session()
nt_cond = (Repository.name == 'svn') & (NamedTree.type == 'branch') & (NamedTree.name == None)
suite_cond = "1=1"
bt_cond = "1=1"

classifier = Classifier(session, nt_cond, suite_cond, bt_cond)

classes = classifier.classify()
for key, value in classes.iteritems():
  print "  {0} - {1} packages".format(key, len(value))
