#! /usr/bin/env python
# vim:ts=2:sw=2:et:ai:sts=2
#
# Copyright 2011, Ansgar Burchardt <ansgar@debian.org>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

from pet.models import *
import pet.update

import argparse
import sys

parser = argparse.ArgumentParser(description='update a repository')
parser.add_argument('-f', '--force', action='store_true', default=False)
parser.add_argument('repositories', nargs='+')
options = parser.parse_args(sys.argv[1:])

session = Session()

try:
  for repo_id in options.repositories:
    repos = session.query(Repository).filter_by(id=repo_id).all()
    for r in repos:
      print "I: Updating repository {0}".format(r.name)
      ru = pet.update.RepositoryUpdater(r, force=options.force)
      ru.run()
  session.commit()
except KeyboardInterrupt:
  print "E: Interrupted."
  session.commit()
except:
  session.rollback()
  raise
