#! /usr/bin/env python
# vim:ts=2:sw=2:et:ai:sts=2
#
# Copyright 2011, Ansgar Burchardt <ansgar@debian.org>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

import pet.models
import pet.update

import argparse

def main():
  parser = argparse.ArgumentParser(description='check watch files')
  parser.add_argument('packages', nargs='*')

  options = parser.parse_args()
  session = pet.models.Session()
  updater = pet.update.WatchUpdater(session)

  try:
    if options.packages:
      named_trees = session.query(pet.models.NamedTree) \
          .join(pet.models.NamedTree.package) \
          .filter(pet.models.Package.name.in_(options.packages))
      updater.run(named_trees)
    else:
      updater.run()
    session.commit()
  except KeyboardInterrupt:
    print "E: Interrupted."
    session.commit()
  except:
    session.rollback()
    raise

if __name__ == '__main__':
  main()

