#! /usr/bin/env python
# vim:ts=2:sw=2:et:ai:sts=2
#
# Copyright 2011, Ansgar Burchardt <ansgar@debian.org>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

from pet.models import *
from pet.vcs import vcs_backend
import pet.update

from argparse import ArgumentParser

parser = ArgumentParser(description='check watch files')
parser.add_argument('packages', nargs='*')

options = parser.parse_args()

session = Session()
wu = pet.update.WatchUpdater(session)

try:
  if options.packages:
    named_trees = session.query(NamedTree).join(NamedTree.package).filter(Package.name.in_(options.packages))
    wu.run(named_trees)
  else:
    wu.run()
  session.commit()
except KeyboardInterrupt:
  print "E: Interrupted."
  session.commit()
except:
  session.rollback()
  raise
