#! /usr/bin/env python

from pet.models import *
from pet.vcs import vcs_backend
import pet.update

import sys

session = Session()
wu = pet.update.WatchUpdater(session)

try:
  wu.run()
  session.commit()
except KeyboardInterrupt:
  print "E: Interrupted."
  session.commit()
except:
  session.rollback()
  raise
