#! /usr/bin/env python

from pet.models import *
from pet.vcs import vcs_backend
import pet.update

import sys

session = Session()

try:
  for repo_name in sys.argv[1:]:
    repos = session.query(Repository).filter_by(name=repo_name).all()
    for r in repos:
      print "I: Updating repository {0}".format(r.name)
      ru = pet.update.RepositoryUpdater(r)
      ru.run()
  session.commit()
except KeyboardInterrupt:
  print "E: Interrupted."
  session.commit()
except:
  session.rollback()
  raise
